name: Update Workshop Catalog from Google Sheets

on:
  schedule:
    # Run daily at 9 AM UTC (2 AM PST)
    - cron: '0 9 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-catalog:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client pyyaml
    
    - name: Fetch workshop catalog from Google Sheets
      env:
        GOOGLE_WORKSHOPS_SHEET_ID: ${{ secrets.GOOGLE_WORKSHOPS_SHEET_ID }}
        GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      run: |
        python scripts/fetch_workshop_catalog.py
    
    - name: Generate workshop pages for new workshops
      run: |
        python scripts/generate_workshop_pages.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add _data/workshops.yml workshop/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update workshop catalog and generate new workshop pages [skip ci]"
          git push
        fi